// import { Box, AlertCircle, ShoppingCart, Truck, Users } from 'lucide-react'; // Import icons

// const StockManagementReport = () => {
//   const stockItems = [
//     { id: 1, name: "Laptop", category: "Electronics", quantity: 10, quantitySold: 5, stockValue: 2000, reorderLevel: 5 },
//     { id: 2, name: "Desk", category: "Furniture", quantity: 5, quantitySold: 2, stockValue: 500, reorderLevel: 2 },
//     { id: 3, name: "Notebook", category: "Stationery", quantity: 50, quantitySold: 25, stockValue: 100, reorderLevel: 10 },
//     { id: 4, name: "Projector", category: "Electronics", quantity: 3, quantitySold: 1, stockValue: 1200, reorderLevel: 2 },
//     { id: 5, name: "Chair", category: "Furniture", quantity: 8, quantitySold: 4, stockValue: 400, reorderLevel: 3 },
//   ];

//   return (
//     <div className="bg-gray-50 min-h-screen p-8">
//       {/* Report Title */}
//       <h1 className="text-4xl font-extrabold text-gray-900 mb-6">Stock Management Report</h1>
//       <p className="text-lg text-gray-700 mb-4">Date Range: January 1, 2025 - January 20, 2025</p>
//       <p className="text-lg text-gray-700 mb-6">Generated By: Stock Management Department | Company: XYZ Corporation</p>

//       {/* Summary and Icon Cards Section */}
//       <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
//         {/* Total Stock Items */}
//         <div className="bg-white shadow-md rounded-lg p-4 flex items-center space-x-4">
//           <Box className="text-blue-600 w-10 h-10" />
//           <div>
//             <h2 className="text-gray-700 text-lg font-semibold">Total Stock Items</h2>
//             <p className="text-gray-500 text-sm">{stockItems.length}</p>
//           </div>
//         </div>

//         {/* Low Stock Alerts */}
//         <div className="bg-white shadow-md rounded-lg p-4 flex items-center space-x-4">
//           <AlertCircle className="text-yellow-600 w-10 h-10" />
//           <div>
//             <h2 className="text-gray-700 text-lg font-semibold">Low Stock Alerts</h2>
//             <p className="text-gray-500 text-sm">{stockItems.filter(item => item.quantity <= item.reorderLevel).length}</p>
//           </div>
//         </div>

//         {/* Items Out of Stock */}
//         <div className="bg-white shadow-md rounded-lg p-4 flex items-center space-x-4">
//           <Box className="text-red-600 w-10 h-10" />
//           <div>
//             <h2 className="text-gray-700 text-lg font-semibold">Out of Stock</h2>
//             <p className="text-gray-500 text-sm">{stockItems.filter(item => item.quantity === 0).length}</p>
//           </div>
//         </div>
//       </div>

//       {/* Stock Overview Table */}
//       <div className="bg-white p-6 rounded-lg shadow-lg mb-8">
//         <h2 className="text-2xl font-semibold text-gray-800 mb-4">Stock Overview</h2>
//         <table className="min-w-full table-auto text-gray-700">
//           <thead className="bg-gray-100">
//             <tr>
//               <th className="px-4 py-2 text-left">Item Name</th>
//               <th className="px-4 py-2 text-left">Category</th>
//               <th className="px-4 py-2 text-left">Quantity Available</th>
//               <th className="px-4 py-2 text-left">Quantity Sold</th>
//               <th className="px-4 py-2 text-left">Stock Value</th>
//               <th className="px-4 py-2 text-left">Reorder Level</th>
//             </tr>
//           </thead>
//           <tbody>
//             {stockItems.map(item => (
//               <tr key={item.id} className="hover:bg-gray-50">
//                 <td className="px-4 py-2 border">{item.name}</td>
//                 <td className="px-4 py-2 border">{item.category}</td>
//                 <td className="px-4 py-2 border">{item.quantity}</td>
//                 <td className="px-4 py-2 border">{item.quantitySold}</td>
//                 <td className="px-4 py-2 border">${item.stockValue}</td>
//                 <td className="px-4 py-2 border">{item.reorderLevel}</td>
//               </tr>
//             ))}
//           </tbody>
//         </table>
//       </div>

//       {/* Actionable Insights Section */}
//       <div className="bg-white p-6 rounded-lg shadow-lg mb-8">
//         <h2 className="text-2xl font-semibold text-gray-800 mb-4">Actionable Insights</h2>
//         <ul className="list-disc pl-5 text-gray-700">
//           <li>Items to reorder: Laptop (5 units), Projector (Replenish stock), Chair (Low stock)</li>
//           <li>Top-Selling Item: Notebook (25 units sold)</li>
//           <li>Suggested Restock: Order 5 more Laptops, 3 more Chairs, and 2 Projectors</li>
//         </ul>
//       </div>

//       {/* Footer Section */}
//       <div className="text-center text-sm text-gray-500">
//         <p>Generated By: Stock Management Team</p>
//         <p>Date of Generation: January 21, 2025</p>
//         <p>XYZ Corporation, Email: support@xyz.com, Phone: (123) 456-7890</p>
//       </div>
//     </div>
//   );
// };

// export default StockManagementReport;
